The source of this tutorial is
https://www.tensorflow.org/tutorials/quickstart/beginner


Check this out later to refresh memory on how tensorflow works. Tensorflow is basically neural network build by google. The backend is called tensor and the API is Kera. 

In [2]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.6078602 ,  0.57473797, -0.37043256,  0.56144637,  0.3208413 ,
        -0.06544743,  0.6192268 ,  0.05385178,  0.7578921 , -0.7175968 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.13206269, 0.12776011, 0.04964928, 0.12607323, 0.09911272,
        0.06735446, 0.13357235, 0.07588874, 0.15343983, 0.03508661]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.6977863

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 107us/sample - loss: 0.2987 - accuracy: 0.9130
Epoch 2/5
60000/60000 [==============================] - 5s 91us/sample - loss: 0.1438 - accuracy: 0.9579
Epoch 3/5
60000/60000 [==============================] - 5s 90us/sample - loss: 0.1074 - accuracy: 0.9670
Epoch 4/5
60000/60000 [==============================] - 5s 91us/sample - loss: 0.0886 - accuracy: 0.9723
Epoch 5/5
60000/60000 [==============================] - 5s 91us/sample - loss: 0.0750 - accuracy: 0.9763


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0770 - accuracy: 0.9763


[0.07699349072049372, 0.9763]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9018273e-07, 2.2329536e-09, 1.3541697e-06, 8.4976222e-05,
        1.7985646e-11, 6.3200268e-08, 5.0473291e-14, 9.9991262e-01,
        4.0404160e-07, 4.8776798e-07],
       [1.5969361e-07, 2.4066528e-06, 9.9999464e-01, 7.5776444e-07,
        1.4729239e-11, 3.1140613e-07, 8.0863053e-08, 1.8767595e-13,
        1.5064212e-06, 1.3130362e-13],
       [1.7595896e-07, 9.9894744e-01, 4.8675982e-05, 1.7281030e-06,
        1.6922576e-04, 1.7647801e-06, 6.6864563e-06, 5.0176150e-04,
        3.1885141e-04, 3.5218552e-06],
       [9.9965727e-01, 1.1854206e-08, 6.7821920e-06, 9.7425684e-08,
        2.2678414e-07, 9.5043661e-06, 3.1996900e-04, 1.3749639e-06,
        3.3991142e-08, 4.6803302e-06],
       [1.8051586e-06, 1.7651844e-08, 2.4519716e-06, 1.3614167e-08,
        9.9887818e-01, 1.1034371e-07, 1.2381444e-05, 8.8133484e-06,
        9.1243476e-07, 1.0952100e-03]], dtype=float32)>